### ISSUE TITLE
"No store class was provided in the config"

### ISSUE THREAD

**Issue by Evidlo** [poljar/weechat-matrix#100]
I got this from a fresh install of the most recent weechat-matrix and matrix-nio.

```
02:43 -- matrix: Logging in...
02:43 python: stdout/stderr (matrix): Traceback (most recent call last):
02:43 python: stdout/stderr (matrix):   File "/home/evan/.weechat/python/matrix/utf.py", line 91, in wrapper
02:43 python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
02:43 python: stdout/stderr (matrix):   File "/home/evan/.weechat/python/matrix.py", line 309, in receive_cb
02:43 python: stdout/stderr (matrix):     response = server.client.next_response(MAX_EVENTS)
02:43 python: stdout/stderr (matrix):   File "/usr/lib/python2.7/site-packages/nio/client/http_client.py", line 1018, in next_response
02:43 python: stdout/stderr (matrix):     self.receive_response(response)
02:43 python: stdout/stderr (matrix):   File "/usr/lib/python2.7/site-packages/nio/client/base_client.py", line 788, in receive_response
02:43 python: stdout/stderr (matrix):     self._handle_login(response)
02:43 python: stdout/stderr (matrix):   File "/usr/lib/python2.7/site-packages/nio/client/base_client.py", line 499, in _handle_login
02:43 python: stdout/stderr (matrix):     self.load_store()
02:43 python: stdout/stderr (matrix):   File "/usr/lib/python2.7/site-packages/nio/client/base_client.py", line 291, in load_store
02:43 python: stdout/stderr (matrix):     raise LocalProtocolError("No store class was provided in the "
02:43 python: stdout/stderr (matrix): nio.exceptions.LocalProtocolError: No store class was provided in the config.
02:43 =!= python: error in function "receive_cb"
```

```
[evan@blackbox ~] pip2 freeze
apsw==3.22.0.post1
arandr==0.1.9
asn1crypto==0.24.0
atomicwrites==1.1.5
attrs==19.1.0
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
BeautifulSoup==3.2.1
beautifulsoup4==4.6.3
bodhi==3.12.0
bodhi-client==3.12.0
bs4==0.0.1
CCColUtils==1.5
cffi==1.11.5
chardet==3.0.4
Cheetah==3.1.0
Cheetah3==3.1.0
click==6.7
cryptography==2.3
cssselect==0.9.2
cssutils==1.0.2
cycler==0.10.0
Cython==0.28.6
decorator==4.2.1
distro==1.2.0
dnspython==1.15.0
docutils==0.14
enum==0.4.4
enum34==1.1.6
fedora-review==0.6.1
fedpkg==1.36
feedparser==5.2.1
file-magic==0.3.0
fuse-python==0.2.1
future==0.16.0
futures==3.2.0
gitdb2==2.0.3
GitPython==2.1.11
gpg==1.10.0
greenlet==0.4.15
h11==0.9.0
h2==3.1.0
hpack==3.0.0
html5-parser==0.4.4
html5lib==0.999999999
httplib2==0.10.3
hyperframe==5.2.0
idna==2.5
iniparse==0.4
ipaddress==1.0.18
ipdb==0.11
ipython==5.8.0
ipython-genutils==0.1.0
jsonschema==2.6.0
kerberos==1.2.5
key-mon==1.16
kitchen==1.2.5
kiwisolver==1.0.1
lockfile==0.11.0
Logbook==1.0.0
lxml==4.2.5
M2Crypto==0.28.2
matplotlib==2.2.3
matrix-nio==0.3
mechanize==0.3.5
mercurial==4.4.2
mistune==0.8.3
msgpack==0.5.6
munch==2.2.0
neovim==0.2.6
netifaces==0.10.6
nose==1.3.7
Nuitka==0.6.1.1
numpy==1.14.5
odfpy==1.3.4
offtrac==0.1.0
olefile==0.46
openidc-client==0.6.0
osc==0.163.0
packagedb-cli==2.14.1
packaging==16.8
path.py==5.2
pathlib==1.0.1
pdfrw==0.4
pexpect==4.3.1
pickleshare==0.7.4
Pillow==5.1.1
ply==3.9
pony==0.7.6
prompt-toolkit==1.0.15
psutil==5.4.3
ptyprocess==0.5.2
PyAudio==0.2.9
pycairo==1.16.3
pycparser==2.14
pycrypto==2.6.1
pycryptodome==3.8.2
pycurl==7.43.0.2
pygame==1.9.4
Pygments==2.2.0
pygobject==3.28.3
pylibacl==0.5.2
pyliblzma==0.5.3
PyOpenGL==3.1.1a1
PyOpenGL-accelerate==3.1.1a1
pyOpenSSL==17.3.0
pyparsing==2.1.10
PySocks==1.6.8
python-bugzilla==2.2.0
python-dateutil==2.7.3
python-fedora==0.10.0
python-xlib==0.20
python-yubico==1.3.2
pytz==2017.2
pyusb==1.0.2
pyxattr==0.5.3
pyxdg==0.25
PyYAML==3.12
pyzmq==17.0.0
regex==2019.1.24
reportlab==3.4.0
repoze.lru==0.4
requests==2.20.0
requests-kerberos==0.12.0
rpkg==1.57
rpm==4.14.2.1
rst2pdf==0.93.dev0
scipy==1.0.0
scour==0.35
Send2Trash==1.4.2
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.10.0
six==1.11.0
smartcols==0.3.0
smmap2==2.0.3
SQLAlchemy==1.2.17
straight.plugin==1.5.0
subprocess32==3.2.6
synce-kpm==0.15.1
synce-sync-engine==0.15.1
syncthing-gtk==0.9.4.3
traitlets==4.3.2
trollius==2.2
typing==3.6.2
uniconvertor==2.0
unpaddedbase64==1.1.0
urlgrabber==3.10.1
urllib3==1.24.1
wcwidth==0.1.7
webcolors==1.7
webencodings==0.5.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
```

**Comment by poljar** [comment]
You don't have python-olm installed and I didn't yet have the chance to modify Weechat to scream if encryption support for nio isn't installed.

**Comment by Evidlo** [comment]
So can I use weechat-matrix without Olm?
