### ISSUE TITLE
Python can't import libolm

### ISSUE THREAD

**Issue by dannycolin** [poljar/weechat-matrix#110]
**Info**
Debian 10
Python 2.7.16

**Step to reproduce**
- Compile *libolm*. Everything when well and *libolm.so.3* installed successfully in */usr/local/lib/*.
- Install, via pip, python-olm (3.1.3) and python-olm-dev (3.0)
- Install matrix.py with `pip install -r requirements.txt`
- Try to load the script with `/script load matrix.py` in weechat

**Actual Result**

Python can't import libolm.so.3

```
python: loading script "/home/sdk/.weechat/python/matrix.py"
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/sdk/.weechat/python/matrix.py", line 34, in <module>
python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType                                                 
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/__init__.py", line 2, in <module>                                   
python: stdout/stderr (?):     from .client import *
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/client/__init__.py", line 3, in <module>                            
python: stdout/stderr (?):     from .base_client import Client, ClientConfig                                                                            
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/client/base_client.py", line 25, in <module>                        
python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED                                                                                  
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/crypto/__init__.py", line 17, in <module>                           
python: stdout/stderr (?):     from .sessions import (
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/crypto/sessions.py", line 24, in <module>                           
python: stdout/stderr (?):     import olm
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/olm/__init__.py", line 12, in <module>                                  
python: stdout/stderr (?):     from .utility import ed25519_verify, OlmVerifyError                                                                      
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/olm/utility.py", line 25, in <module>                                   
python: stdout/stderr (?):     from _libolm import ffi, lib  # type: ignore
python: stdout/stderr (?): ImportError: libolm.so.3: cannot open shared object file: No such file or directory                                          
python: unable to parse file "/home/sdk/.weechat/python/matrix.py"
```

**Expected Result**

Python should load matrix.py

**Comment by trygveaa** [comment]
Try running `ldconfig` to update the library cache. You may also have to restart weechat.

**Comment by dannycolin** [comment]
> Try running `ldconfig` to update the library cache. You may also have to restart weechat.

Ah thanks! Completely forgot about that `ldconfig` thingy. So I got an error with nio and I `pip install nio` to resolve it but now I'm stuck at:

```
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/sdk/.weechat/python/matrix.py", line 34, in <module>
python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/__init__.py", line 1, in <module>
python: stdout/stderr (?):     from nio.block.base import Block
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/block/base.py", line 12, in <module>
python: stdout/stderr (?):     from nio.command import command
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/command/__init__.py", line 1, in <module>
python: stdout/stderr (?):     from nio.command.decorator import command
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/command/decorator.py", line 1, in <module>
python: stdout/stderr (?):     from nio.command.base import Command
python: stdout/stderr (?):   File "/home/sdk/.local/lib/python2.7/site-packages/nio/command/base.py", line 29
python: stdout/stderr (?):     def __init__(self, id, *params, title=None, method=None):
python: stdout/stderr (?):
python: stdout/stderr (?): SyntaxError: invalid syntax
```

Any idea?

**Comment by poljar** [comment]
Did you perhaps install https://pypi.org/project/nio/ instead of https://pypi.org/project/matrix-nio/?

**Comment by dannycolin** [comment]
Both are installed

**Comment by poljar** [comment]
You'll have to get rid of https://pypi.org/project/nio/ or run weechat inside a virtualenv: https://github.com/poljar/weechat-matrix/issues/105

**Comment by dannycolin** [comment]
@poljar but I had to install it to avoid the following error : 

`ImportError: No module named nio`

**Comment by poljar** [comment]
You had to install matrix-nio[https://pypi.org/project/matrix-nio/], not nio[https://pypi.org/project/nio/]. The second one is completely unrelated to Matrix.

**Comment by dannycolin** [comment]
> You had to install [matrix-nio](https://pypi.org/project/matrix-nio/), not [nio](https://pypi.org/project/nio/). The second one is completely unrelated to Matrix.

@poljar This is exactly what I've done. I've uninstalled `nio` and installed `matrix-nio`. Doing so, give me the `ImportError: No module named nio` when I try to load the script.

**Comment by poljar** [comment]
Does importing nio from a python interpreter work? Are you sure that matrix-nio is installed.

**Comment by dannycolin** [comment]
> Does importing nio from a python interpreter work?

`ImportError: No module named nio`

> Are you sure that matrix-nio is installed.

And yes, it is install `matrix-nio     0.4.1`

**Comment by poljar** [comment]
An installed python module can usually be imported. Can you try reinstalling? How are you checking if it's installed? Is it installed in a location where the python interpreter will look for it?
