### ISSUE TITLE
python error on loading script in weechat

### ISSUE THREAD

**Issue by ay3w** [poljar/weechat-matrix#120]
```
21:13:47 |   | python: loading script "/home/ayew/.weechat/python/matrix.py"
-- | -- | --
21:13:47 |   | python: stdout/stderr (?): Traceback (most recent call last):
21:13:47 |   | python: stdout/stderr (?):   File "/home/ayew/.weechat/python/matrix.py", line 53, in <module>
21:13:47 |   | python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
21:13:47 |   | python: stdout/stderr (?):   File "/home/ayew/.local/lib/python3.7/site-packages/nio/__init__.py", line 2, in <module>
21:13:47 |   | python: stdout/stderr (?):     from .client import *
21:13:47 |   | python: stdout/stderr (?):   File "/home/ayew/.local/lib/python3.7/site-packages/nio/client/__init__.py", line 3, in <module>
21:13:47 |   | python: stdout/stderr (?):     from .base_client import Client, ClientConfig
21:13:47 |   | python: stdout/stderr (?):   File "/home/ayew/.local/lib/python3.7/site-packages/nio/client/base_client.py", line 25, in <module>
21:13:47 |   | python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
21:13:47 |   | python: stdout/stderr (?):   File "/home/ayew/.local/lib/python3.7/site-packages/nio/crypto/__init__.py", line 17, in <module>
21:13:47 |   | python: stdout/stderr (?):     from .sessions import (
21:13:47 |   | python: stdout/stderr (?):   File "/home/ayew/.local/lib/python3.7/site-packages/nio/crypto/sessions.py", line 24, in <module>
21:13:47 |   | python: stdout/stderr (?):     import olm
21:13:47 |   | python: stdout/stderr (?):   File "/usr/local/lib/python3.7/dist-packages/olm/__init__.py", line 24, in <module>
21:13:47 |   | python: stdout/stderr (?):     from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
21:13:47 |   | python: stdout/stderr (?):   File "/usr/local/lib/python3.7/dist-packages/olm/utility.py", line 39, in <module>
21:13:47 |   | python: stdout/stderr (?):     from _libolm import ffi, lib  # type: ignore
21:13:47 |   | python: stdout/stderr (?): ImportError: /usr/local/lib/python3.7/dist-packages/_libolm.abi3.so: undefined symbol: olm_clear_pk_signing
21:13:47 | =!= | python: unable to parse file "/home/ayew/.weechat/python/matrix.py"
```

**Comment by poljar** [comment]
There's a version mismatch between the Olm library that was used to compile python-olm and the one that is used when running.

You can check that this isn't weechat-matrix specific by importing the `olm` module from a python interpreter:

    >>> import olm

This closed issue has more details on what's going on: https://github.com/poljar/python-olm/issues/8

**Comment by ay3w** [comment]
Ah.

I tried to use the libolm-dev package in the debian buster repository, without checking the version met the requirements (it was on 2.2.2). Then I tried to build in from source and somehow ended up with conflicted versions.

In the end, I installed libolm-dev 3.1.3 from testing/bullseye.
