### ISSUE TITLE
Make Dockerfile use requirements.txt

### ISSUE THREAD

**Issue by anoadragon453** [poljar/weechat-matrix#122]
```
         │10:26:51     | python: loading script "/root/weechat-conf/python/matrix.py"
         │10:26:51     | python: stdout/stderr (?): Traceback (most recent call last):
         │10:26:51     | python: stdout/stderr (?):   File "/root/weechat-conf/python/matrix.py", line 53, in <module>
         │10:26:51     | python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
         │10:26:51     | python: stdout/stderr (?):   File "/usr/local/lib/python2.7/dist-packages/nio/__init__.py", line 2, in <module>
         │10:26:51     | python: stdout/stderr (?):     from .client import *
         │10:26:51     | python: stdout/stderr (?):   File "/usr/local/lib/python2.7/dist-packages/nio/client/__init__.py", line 3, in <module>
         │10:26:51     | python: stdout/stderr (?):     from .base_client import Client, ClientConfig
         │10:26:51     | python: stdout/stderr (?):   File "/usr/local/lib/python2.7/dist-packages/nio/client/base_client.py", line 25, in <module>
         │10:26:51     | python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
         │10:26:51     | python: stdout/stderr (?):   File "/usr/local/lib/python2.7/dist-packages/nio/crypto/__init__.py", line 37, in <module>
         │10:26:51     | python: stdout/stderr (?):     from .olm_machine import Olm
         │10:26:51     | python: stdout/stderr (?):   File "/usr/local/lib/python2.7/dist-packages/nio/crypto/olm_machine.py", line 30, in <module>
         │10:26:51     | python: stdout/stderr (?):     from cachetools import LRUCache
         │10:26:51     | python: stdout/stderr (?): ImportError: No module named cachetools
         │10:26:51 =!= | python: unable to parse file "/root/weechat-conf/python/matrix.py"
```

**Comment by anoadragon453** [comment]
Fixed in https://github.com/poljar/weechat-matrix/pull/148
