### ISSUE TITLE
error in function "matrix_config_server_change_cb"

### ISSUE THREAD

**Issue by binaryplease** [poljar/weechat-matrix#134]
Installed on arch via aur package. When doing `/script load matrix.py` I get this error:

```
00:33 Plugins loaded: alias, buflist, charset, exec, fifo, fset, guile, irc, logger, lua, perl, python, relay, ruby, script, spell, tcl, trigger, xfer
00:34 python: loading script "/home/binaryplease/.weechat/python/matrix.py"
00:34 python: registered script "matrix", version 0.1 (matrix chat plugin)
00:34 python: stdout/stderr (matrix): Traceback (most recent call last):
00:34 python: stdout/stderr (matrix):   File "/home/binaryplease/.weechat/python/matrix/utf.py", line 89, in wrapper
00:34 python: stdout/stderr (matrix):     return function(*args, **kwargs)
00:34 python: stdout/stderr (matrix):   File "/home/binaryplease/.weechat/python/matrix/server.py", line 1558, in matrix_config_server_change_cb
00:34 python: stdout/stderr (matrix):     server.update_option(option, option_name)
00:34 python: stdout/stderr (matrix):   File "/home/binaryplease/.weechat/python/matrix/server.py", line 365, in update_option
00:34 python: stdout/stderr (matrix):     self._change_client()
00:34 python: stdout/stderr (matrix):   File "/home/binaryplease/.weechat/python/matrix/server.py", line 355, in _change_client
00:34 python: stdout/stderr (matrix):     self.client = HttpClient(
00:34 python: stdout/stderr (matrix): TypeError: __init__() got an unexpected keyword argument 'extra_path'
00:34  !!!  python: error in function "matrix_config_server_change_cb"

```

**Comment by poljar** [comment]
There's something old here, either nio or weechat-matrix.

**Comment by binaryplease** [comment]
Thanks, fixed by reinstall.
