### ISSUE TITLE
Type Error: Attrib() got an unexpected keyword argument 'factory'

### ISSUE THREAD

**Issue by 4D617278** [poljar/weechat-matrix#142]
ubuntu@ubuntu:~/weechat-matrix$ python main.py

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    from nio import RemoteProtocolError, RemoteTransportError, TransportType
  File "/usr/local/lib/python2.7/dist-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/usr/local/lib/python2.7/dist-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig
  File "/usr/local/lib/python2.7/dist-packages/nio/client/base_client.py", line 25, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/usr/local/lib/python2.7/dist-packages/nio/crypto/__init__.py", line 37, in <module>
    from .olm_machine import Olm
  File "/usr/local/lib/python2.7/dist-packages/nio/crypto/olm_machine.py", line 46, in <module>
    from ..responses import (KeysClaimResponse, KeysQueryResponse,
  File "/usr/local/lib/python2.7/dist-packages/nio/responses.py", line 822, in <module>
    class KeysQueryResponse(Response):
  File "/usr/local/lib/python2.7/dist-packages/nio/responses.py", line 828, in KeysQueryResponse
    factory=dict
TypeError: attrib() got an unexpected keyword argument 'factory'

All requirements already installed, running main.py throws this error

**Comment by poljar** [comment]
You seem to have an older version of attrs installed, the factory argument was added in 18.1 as per docs:
> New in version 18.1.0: factory=f is syntactic sugar for default=attr.Factory(f).

**Comment by 4D617278** [comment]
How does one learn how to resolve such errors on their own? How do you find the solution in the docs so quickly?

**Comment by poljar** [comment]
Well the error is telling me to look up when the keyword argument `factory` was added since I know that it indeed isn't unknown.

**Comment by 4D617278** [comment]
How did you know the problem was in attrs?

**Comment by poljar** [comment]
The last line of the traceback tells you this:
>  TypeError: attrib() got an unexpected keyword argument 'factory'

`attrib()` is a method in attrs.

**Comment by 4D617278** [comment]
Thanks, after updating attrs I got new error when trying to run main.py:
$ main.py
Traceback (most recent call last):
  File "main.py", line 679, in <module>
    if W.register(WEECHAT_SCRIPT_NAME, WEECHAT_SCRIPT_AUTHOR,
AttributeError: 'module' object has no attribute 'register'

$ python
>> from matrix.globals import W
>> help(W)
>>hasattr('W','register')
False

**Comment by poljar** [comment]
This can't be run stand alone, it's a Weechat script. You'll need to load it from within Weechat.

[This](https://github.com/poljar/weechat-matrix#configuration) section of the readme shows how to do it. I completely missed that from the first traceback.

You might also want to read up on Weechat usage in general.

**Comment by 4D617278** [comment]
Thanks, never mind I got it
