### ISSUE TITLE
Python-crypto

### ISSUE THREAD

**Issue by trmendes** [poljar/weechat-matrix#15]
I don't know much about python so I'm not sure if it is something I'm doing wrong or not.

I'm running Archlinux and I do have python-crypto installed

if I open a python cli and type import OpenSSL.crypto I get no errors
but when I run
/script load matrix.py on my weechat I see this message: No module named OpenSSL.crypto

Just wondering what I'm doing wrong here.

log messages:
```
20:45 python: loading script "/home/thiago/.dotfiles/weechat/python/matrix.py"
20:45 python: stdout/stderr (colorize_nicks): Traceback (most recent call last):
20:45 python: stdout/stderr (?): Traceback (most recent call last):
20:45 python: stdout/stderr (colorize_nicks):   File "/home/thiago/.dotfiles/weechat/python/matrix.py", line 24, in <module>
20:45 python: stdout/stderr (?):   File "/home/thiago/.dotfiles/weechat/python/matrix.py", line 24, in <module>
20:45 python: stdout/stderr (colorize_nicks):     import OpenSSL.crypto as crypto
20:45 python: stdout/stderr (?):     import OpenSSL.crypto as crypto
20:45 python: stdout/stderr (colorize_nicks): ImportError: No module named OpenSSL.crypto
20:45 python: stdout/stderr (?): ImportError: No module named OpenSSL.crypto
20:45 =!= python: unable to parse file "/home/thiago/.dotfiles/weechat/python/matrix.py"
```

**Comment by dkasak** [comment]
weechat uses python2, so you need to have python2 modules installed. In this case, `python2-crypto`.
