### ISSUE TITLE
Test failure (something to do with python-typing): "AttributeError: type object 'Callable' has no attribute '_abc_registry'"

### ISSUE THREAD

**Issue by pkillnine** [poljar/weechat-matrix#153]
Python version is 3.7.4

```
python3 -m pytest
Traceback (most recent call last):
  File "/gnu/store/78w7y0lxar70j512iqw8x3nimzj10yga-python-3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/gnu/store/78w7y0lxar70j512iqw8x3nimzj10yga-python-3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/pytest.py", line 89, in <module>
    raise SystemExit(pytest.main())
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/_pytest/config/__init__.py", line 679, in pytest_cmdline_parse
    self.parse(args)
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/_pytest/config/__init__.py", line 896, in parse
    self._preparse(args, addopts=addopts)
  File "/gnu/store/wrllykvq4l9ia5wldivmdlwgf2c8m2mb-python-pytest-4.4.2/lib/python3.7/site-packages/_pytest/config/__init__.py", line 841, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/gnu/store/w80vzg9kysnk379pn71b7pgn6l2jr6dx-python-pluggy-0.11.0/lib/python3.7/site-packages/pluggy/manager.py", line 274, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/gnu/store/78w7y0lxar70j512iqw8x3nimzj10yga-python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/gnu/store/78w7y0lxar70j512iqw8x3nimzj10yga-python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/gnu/store/w685cz0qf653xw1dinggddizj994jcb1-python-hypothesis-4.18.3/lib/python3.7/site-packages/hypothesis/__init__.py", line 27, in <module>
    from hypothesis._settings import HealthCheck, Phase, Verbosity, settings, unlimited
  File "/gnu/store/w685cz0qf653xw1dinggddizj994jcb1-python-hypothesis-4.18.3/lib/python3.7/site-packages/hypothesis/_settings.py", line 40, in <module>
    from hypothesis.internal.compat import integer_types, quiet_raise, string_types
  File "/gnu/store/w685cz0qf653xw1dinggddizj994jcb1-python-hypothesis-4.18.3/lib/python3.7/site-packages/hypothesis/internal/compat.py", line 296, in <module>
    import typing
  File "/gnu/store/fbc8avyhx8cdqwq499wfdmzyhjv95dgs-python-typing-3.6.6/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/gnu/store/fbc8avyhx8cdqwq499wfdmzyhjv95dgs-python-typing-3.6.6/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
make: *** [Makefile:31: test] Error 1
command "/gnu/store/b5vpfzkr59bpgcsg1k9vvad9h5rwvpgk-make-4.2.1/bin/make" "test" failed with status 2
```

**Comment by pkillnine** [comment]
Fixed by removing python-typing, which apparently causes problems with python version 3.7 and isn't needed.

I also removed python-dataclasses as suggested here: https://stackoverflow.com/a/58067012 due to a new error mentioned in that link (`AttributeError: module 'typing' has no attribute '_ClassVar'`)
