### ISSUE TITLE
ImportError: cannot import name 'Deque'

### ISSUE THREAD

**Issue by anadahz** [poljar/weechat-matrix#154]
On git commit: https://github.com/poljar/weechat-matrix/commit/46640df3e0bfb058e97d8abe723bb88fdf4e5177

```
python: loading script "/home/user/.weechat/python/matrix.py"
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/user/.weechat/python/matrix.py", line 39, in <module>
python: stdout/stderr (?):     from typing import Any, AnyStr, Deque, Dict, List, Optional, Set, Text, Tuple
python: stdout/stderr (?): ImportError: cannot import name 'Deque'
python: unable to parse file "/home/user/.weechat/python/matrix.py"
```

`/version`
`WeeChat 2.7 [compiled on Dec  8 2019 10:38:40]`

`/python version`
`python: 3.5.3`

`$ pip3 freeze`

```
aiohttp==3.6.2
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.3.0
cachetools==4.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
dataclasses==0.6
future==0.18.2
h11==0.9.0
h2==3.1.1
hpack==3.0.0
hyperframe==5.2.0
idna==2.8
idna-ssl==1.1.0
importlib-metadata==1.5.0
jsonschema==3.2.0
keyring==10.1
keyrings.alt==1.3
Logbook==1.5.3
matrix-nio==0.7.1
multidict==4.7.4
peewee==3.13.1
pyasn1==0.1.9
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.9.4
Pygments==2.5.2
pygobject==3.22.0
pyOpenSSL==19.1.0
pyrsistent==0.15.7
python-magic==0.4.15
python-olm==3.1.3
python-potr==1.0.1
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.14.0
typing-extensions==3.7.4.1
unpaddedbase64==1.1.0
urllib3==1.25.8
virtualenv==15.1.0
webcolors==1.10
websocket-client==0.37.0
yarl==1.4.2
zipp==1.1.0
```

**Comment by poljar** [comment]
I think you need the `typing` module, not just `typing-extensions`.

**Comment by anadahz** [comment]
Exact same error as in https://github.com/poljar/weechat-matrix/issues/154#issue-558333331 upon installing the `typing` module.

`$ pip3 freeze`

```
aiohttp==3.6.2
async-timeout==3.0.1
atomicwrites==1.3.0                       
attrs==19.3.0                               
cachetools==4.0.0                                                         
certifi==2019.11.28                                                 
cffi==1.13.2                                                              
chardet==3.0.4                                                            
cryptography==2.8                                                               
dataclasses==0.6                                                                  
future==0.18.2                                                          
h11==0.9.0                                                                                    
h2==3.1.1                                                                     
hpack==3.0.0                                                                  
hyperframe==5.2.0                                                           
idna==2.8                                                                 
idna-ssl==1.1.0                                                             
importlib-metadata==1.5.0                                                     
jsonschema==3.2.0                                         
keyring==10.1                
keyrings.alt==1.3
Logbook==1.5.3
matrix-nio==0.7.1
multidict==4.7.4
peewee==3.13.1
pyasn1==0.1.9
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.9.4
Pygments==2.5.2
pygobject==3.22.0
pyOpenSSL==19.1.0
pyrsistent==0.15.7
python-magic==0.4.15
python-olm==3.1.3
python-potr==1.0.1
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.14.0
typing==3.7.4.1
typing-extensions==3.7.4.1
```

**Comment by poljar** [comment]
I guess your Python is just too old to support Deque.

You can try commenting out this line https://github.com/poljar/weechat-matrix/blob/master/main.py#L39.

Those type hints aren't really necessary to run the script but you might get into trouble somewhere else since nio isn't tested with such an old Python 3 version.

**Comment by anadahz** [comment]
Commenting out https://github.com/poljar/weechat-matrix/blob/master/main.py#L39 brings a different error:

```
python: loading script "/home/user/.weechat/python/matrix.py"
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/user/.weechat/python/matrix.py", line 54, in <module>
python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
python: stdout/stderr (?):   File "/home/user/.local/lib/python3.5/site-packages/nio/__init__.py", line 2, in <module>
python: stdout/stderr (?):     from .client import *
python: stdout/stderr (?):   File "/home/user/.local/lib/python3.5/site-packages/nio/client/__init__.py", line 3, in <module>
python: stdout/stderr (?):     from .base_client import Client, ClientConfig
python: stdout/stderr (?):   File "/home/user/.local/lib/python3.5/site-packages/nio/client/base_client.py", line 167
python: stdout/stderr (?):     self.access_token: str = ""
python: stdout/stderr (?):                      ^
python: stdout/stderr (?): SyntaxError: invalid syntax
python: unable to parse file "/home/user/.weechat/python/matrix.py"
```

**Comment by poljar** [comment]
If that's the only occurrence you can try [0.7](https://pypi.org/project/matrix-nio/0.7/) of nio. Otherwise an even older one will be needed.

**Comment by anadahz** [comment]
I upgraded to newer versions, thus this issue is no longer relevant.

**Comment by trygveaa** [comment]
This is a bit late since you have solved it (I didn't notice the issue until now), but if anyone else experience this and don't want to upgrade, you can fix it by adding this after `from __future__` in `main.py`:

```
import sys
sys.modules["typing.Deque"] = None
```

**Comment by flxai** [comment]
@trygveaa I just tried your suggestion, but it doesn't make any difference. I still get the same error as the OP. I cloned `master` and added the two lines right after this one in `main.py`:

```
from __future__ import unicode_literals
```

**Comment by trygveaa** [comment]
@flxai: I don't see how that could happen. Are you sure you changed the file that weechat loads? The lines I wrote effectively imports `Deque` with a value of `None`, so a subsequent import will be a noop. You can verify it by trying it in a python shell:

```
$ python
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.modules["typing.Deque"] = None
>>> from typing import Any, AnyStr, Deque, Dict, List, Optional, Set, Text, Tuple
>>>
```

Do you get an error if you do that?

**Comment by flxai** [comment]
Sorry, my bad. I edited the wrong file.
