### ISSUE TITLE
the script won't load properly

### ISSUE THREAD

**Issue by TheWing** [poljar/weechat-matrix#169]
I followed the installation procedure, and when finding out that the debian repository version of olm might be too old, compiled that from its git source. Other than that not working on the first try, everything should be as close to the instructions I can get, however: When trying to run /load script matrix.py, this happens.

```
16:05 python: loading script "/home/wing/.weechat_matrix/python/matrix.py"
16:05 python: stdout/stderr (?): Traceback (most recent call last):
16:05 python: stdout/stderr (?):   File "/home/wing/.weechat_matrix/python/matrix.py", line 53, in <module>
16:05 python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/nio/__init__.py", line 2, in <module>
16:05 python: stdout/stderr (?):     from .client import *
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/nio/client/__init__.py", line 3, in <module>
16:05 python: stdout/stderr (?):     from .base_client import Client, ClientConfig
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/nio/client/base_client.py", line 25, in <module>
16:05 python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/nio/crypto/__init__.py", line 23, in <module>
16:05 python: stdout/stderr (?):     from .sessions import (
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/nio/crypto/sessions.py", line 24, in <module>
16:05 python: stdout/stderr (?):     import olm
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/olm/__init__.py", line 24, in <module>
16:05 python: stdout/stderr (?):     from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
16:05 python: stdout/stderr (?):   File "/home/wing/.local/lib/python3.7/site-packages/olm/utility.py", line 39, in <module>
16:05 python: stdout/stderr (?):     from _libolm import ffi, lib  # type: ignore
16:05 python: stdout/stderr (?): ImportError: /home/wing/.local/lib/python3.7/site-packages/_libolm.abi3.so: undefined symbol: olm_clear_pk_signing
```

This still seems to point to something being wrong with the olm things, but I'm not sure where to look.

**Comment by poljar** [comment]
This seems to be the same issue as https://github.com/poljar/weechat-matrix/issues/120#issuecomment-537453156.

**Comment by TheWing** [comment]
ah indeed it does, just saw that myself too. I'll see if I can get it to work with the same solution

**Comment by TheWing** [comment]
Yep, that did it.. I wonder what gets mixed up when you compile libolm3 from sources compared to installing it from the repositories.

Anyhow, this works now, closing.
