### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by demlak** [poljar/weechat-matrix#182]
hey..

since a few days i get several errors like this
```
17:21 =!= python: Fehler in Funktion "typing_notification_cb"
17:21 python: stdout/stderr: (matrix): Traceback (most recent call last):
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/h2/connection.py", line 224, in process_input
17:21 python: stdout/stderr: (matrix):     func, target_state = self._transitions[(self.state, input_)]
17:21 python: stdout/stderr: (matrix): KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_HEADERS: 0>)
17:21 python: stdout/stderr: (matrix): During handling of the above exception, another exception occurred:
17:21 python: stdout/stderr: (matrix): Traceback (most recent call last):
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.weechat/python/autoload/matrix.py", line 618, in typing_notification_cb
17:21 python: stdout/stderr: (matrix):     server.room_send_typing_notice(room_buffer)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.weechat/python/matrix/server.py", line 1019, in room_send_typing_notice
17:21 python: stdout/stderr: (matrix):     _, request = self.client.room_typing(
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/nio/client/http_client.py", line 86, in wrapper
17:21 python: stdout/stderr: (matrix):     return func(self, *args, **kwargs)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/nio/client/base_client.py", line 65, in wrapper
17:21 python: stdout/stderr: (matrix):     return func(self, *args, **kwargs)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/nio/client/http_client.py", line 620, in room_typing
17:21 python: stdout/stderr: (matrix):     return self._send(request, RequestInfo(
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/nio/client/http_client.py", line 86, in wrapper
17:21 python: stdout/stderr: (matrix):     return func(self, *args, **kwargs)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/nio/client/http_client.py", line 149, in _send
17:21 python: stdout/stderr: (matrix):     ret_uuid, data = self.connection.send(request, uuid)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/nio/http.py", line 491, in send
17:21 python: stdout/stderr: (matrix):     self._connection.send_headers(stream_id, request._request)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/h2/connection.py", line 766, in send_headers
17:21 python: stdout/stderr: (matrix):     self.state_machine.process_input(ConnectionInputs.SEND_HEADERS)
17:21 python: stdout/stderr: (matrix):   File "/home/demlak/.local/lib/python3.8/site-packages/h2/connection.py", line 228, in process_input
17:21 python: stdout/stderr: (matrix):     raise ProtocolError(
17:21 python: stdout/stderr: (matrix): h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
```

i'm on a completly updated arch linux..
any ideas?

thx a lot

**Comment by poljar** [comment]
That sounds like it's trying to send typing notifications while being disconnected. Does it happen all the time or is it sporadic?

**Comment by demlak** [comment]
it's sporadic..

is this more helpfull?

```
22:45 =!= matrix: Invalid input ConnectionInputs.RECV_HEADERS in state ConnectionState.CLOSED
22:45 -- matrix: disconnected from server
22:45 -- matrix: reconnecting to server in 10 seconds
22:45 -- matrix: reconnecting to server...
22:45 -- matrix: Connecting to matrix.mymatrixserver.de:443 (SSL)...
22:45 -- matrix: Doing SSL handshake...
22:45 -- matrix: Connected using TLSv1.3, and 256 bit TLS_AES_256_GCM_SHA384 cipher suite.
22:45 -- matrix: received certificate
22:45  - certificate info:
22:45     - subject: commonName=matrix.mymatrixserver.de, serial number
22:45         0365ECF019ADE07B9C690BF693772ABE22AA
22:45     - issuer: countryName=US, organizationName=Let's Encrypt,
22:45         commonName=Let's Encrypt Authority X3
22:45     - key info: RSA key 4096 bits, signed using
22:45         sha256WithRSAEncryption
22:45     - period of validity:
22:45         Begins on:  Mar 25 15:34:16 2020 GMT
22:45         Expires on: Jun 23 15:34:16 2020 GMT
22:45     - fingerprints:
22:45         SHA1:   00:00:00......
22:45         SHA256: 00:00:00:00......
22:45 -- matrix: Already logged in, syncing...
```

**Comment by poljar** [comment]
That's a normal disconnect as it seems. You're running your own server so you should set up HTTP 2 and increase [this setting](http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests) to a high number. This should get rid of the frequent disconnects.

**Comment by demlak** [comment]
well.. it seems the disconnects are initiated while typing.. 

when i just let weechat matrix open and don't type anything, the connection is stable for hours without a single disconnect. but when i start typing, i get disconnect and hundrets of error lines 

any idea how to debug?

**Comment by poljar** [comment]
Passing your connection through [mitmproxy](https://mitmproxy.org) might give some visibility on how many requests are going out. This almost sounds like it's hammering out typing requests which it shouldn't be doing as far as I remember.

**Comment by demlak** [comment]
thx for your info. I recently did a system-update and it seems, that the problem does not exist anymore. Maybe this is over now and it was related to any python modul.
