### ISSUE TITLE
Can't load matrix.py script

### ISSUE THREAD

**Issue by caywin25** [poljar/weechat-matrix#194]
Hello,

I followed the installation documentation and when I want to load the matrix.py script I get the following error: 

```
08:49 python: loading script "/home/matthew/.weechat/python/matrix.py"
08:49 python: stdout/stderr (?): Traceback (most recent call last):
08:49 python: stdout/stderr (?):   File "/home/matthew/.weechat/python/matrix.py", line 55, in <module>
08:49 python: stdout/stderr (?):     from matrix import globals as G
08:49 python: stdout/stderr (?):   File "/home/matthew/.weechat/python/matrix.py", line 55, in <module>
08:49 python: stdout/stderr (?):     from matrix import globals as G
08:49 python: stdout/stderr (?): ImportError: cannot import name 'globals' from 'matrix' (/home/matthew/.weechat/python/matrix.py)
08:49 =!= python: unable to parse file "/home/matthew/.weechat/python/matrix.py"
```
I have python 3.7.4 installed and pip packages installed : 

```
$ pip freeze
aiofiles==0.4.0
aiohttp==3.6.2
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==19.3.0
cachetools==4.1.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
configparser2==4.0.0
cryptography==2.9.2
future==0.18.2
h11==0.9.0
h2==3.2.0
hpack==3.0.0
hyperframe==5.2.0
idna==2.9
importlib-metadata==1.6.0
jsonschema==3.2.0
Logbook==1.5.3
matrix-nio==0.11.2
multidict==4.7.6
peewee==3.13.3
pycparser==2.20
pycryptodome==3.9.7
Pygments==2.6.1
pyOpenSSL==19.1.0
pyrsistent==0.16.0
python-magic==0.4.18
python-olm==3.1.3
requests==2.23.0
six==1.14.0
unpaddedbase64==1.1.0
urllib3==1.25.9
webcolors==1.11.1
yarl==1.4.2
zipp==3.1.0
```
Thank you for your help.

**Comment by trygveaa** [comment]
Seems like you just have the `matrix.py` file in `~/.weechat/python`, and not the `matrix` directory?

**Comment by caywin25** [comment]
Ah yes my bad its works.

Thank you :)
