### ISSUE TITLE
Weechat-matrix failing with weechat2.9 and python 3.8.5

### ISSUE THREAD

**Issue by kenrestivo** [poljar/weechat-matrix#231]
```
20:40   ___       __         ______________        _____ 
20:40   __ |     / /___________  ____/__  /_______ __  /_
20:40   __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  __/
20:40   __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_  
20:40   ____/|__/  \___/\___/\____/  /_/ /_/\__,_/ \__/  
20:40 WeeChat 2.9 [compiled on Aug 15 2020 20:31:09]
20:40 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
20:40 python: stdout/stderr (?): Traceback (most recent call last):
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/playhouse/sqliteq.py", line 7, in <module>
20:40 python: stdout/stderr (?):     from Queue import Queue
20:40 python: stdout/stderr (?): ModuleNotFoundError: No module named 'Queue'
20:40 python: stdout/stderr (?): During handling of the above exception, another exception occurred:
20:40 python: stdout/stderr (?): Traceback (most recent call last):
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/autoload/matrix.py", line 53, in <module>
20:40 python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/__init__.py", line 2, in <module>
20:40 python: stdout/stderr (?):     from .client import *
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/client/__init__.py", line 3, in <module>
20:40 python: stdout/stderr (?):     from .base_client import Client, ClientConfig
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/client/base_client.py", line 35, in <module>
20:40 python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/crypto/__init__.py", line 41, in <module>
20:40 python: stdout/stderr (?):     from .olm_machine import Olm
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/crypto/olm_machine.py", line 52, in <module>
20:40 python: stdout/stderr (?):     from ..store import MatrixStore
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/store/__init__.py", line 35, in <module>
20:40 python: stdout/stderr (?):     from .database import (
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/store/database.py", line 22, in <module>
20:40 python: stdout/stderr (?):     from playhouse.sqliteq import SqliteQueueDatabase
20:40 python: stdout/stderr (?):     from Queue import Queue
20:40 python: stdout/stderr (?): ModuleNotFoundError: No module named 'Queue'
20:40 python: stdout/stderr (?): During handling of the above exception, another exception occurred:
20:40 python: stdout/stderr (?): Traceback (most recent call last):
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/autoload/matrix.py", line 53, in <module>
20:40 python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/__init__.py", line 2, in <module>
20:40 python: stdout/stderr (?):     from .client import *
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/client/__init__.py", line 3, in <module>
20:40 python: stdout/stderr (?):     from .base_client import Client, ClientConfig
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/client/base_client.py", line 35, in <module>
20:40 python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/crypto/__init__.py", line 41, in <module>
20:40 python: stdout/stderr (?):     from .olm_machine import Olm
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/crypto/olm_machine.py", line 52, in <module>
20:40 python: stdout/stderr (?):     from ..store import MatrixStore
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/store/__init__.py", line 35, in <module>
20:40 python: stdout/stderr (?):     from .database import (
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/nio/store/database.py", line 22, in <module>
20:40 python: stdout/stderr (?):     from playhouse.sqliteq import SqliteQueueDatabase
20:40 python: stdout/stderr (?):   File "/home/lken/.weechat/python/venv/lib/python3.8/site-packages/playhouse/sqliteq.py", line 9, in <module>
20:40 python: stdout/stderr (?):     from queue import Queue
20:40 python: stdout/stderr (?):   File "/usr/share/weechat/python/queue.py", line 277
20:40 python: stdout/stderr (?):     if args == "":
20:40 python: stdout/stderr (?):                  ^
20:40 python: stdout/stderr (?): TabError: inconsistent use of tabs and spaces in indentation
20:40 =!= python: unable to parse file "/home/lken/.weechat/python/autoload/matrix.py"
20:40 lua scripts loaded: urlselect
20:40 Plugins loaded: alias, buflist, charset, exec, fifo, fset, irc, logger, lua, perl, python, relay, ruby, script, spell, trigger, xfer
```

Wat?

**Comment by kenrestivo** [comment]
Want to know what the workaround was?

```
sudo rm /usr/share/weechat/python/queue.py
```

And now matrix loads and all the plugins do too. WTF?

**Comment by poljar** [comment]
While we do use the `Queue` module it isn't part of the project. I can't really answer how you installed `queue.py` there.

**Comment by wlallemand** [comment]
I had the same problem, queue.py is part of the weechat-scripts package in debian, which cause this issue.

**Comment by cpiber** [comment]
Same on WeeChat 3.0

**Comment by strk** [comment]
Same on WeeChat 3.4

**Comment by trygveaa** [comment]
I don't think there's much weechat-matrix can do about this. In WeeChats script repo the `queue.py` script has been renamed to `cmdqueue.py` to fix the problem, so the remaining problem is with the `weechat-scripts` package in your distro. Either uninstall this `weechat-scripts` package, or report a bug to Debian or follow [the Ubuntu bug report here](https://bugs.launchpad.net/ubuntu/+source/weechat-scripts/+bug/1903354).
