### ISSUE TITLE
<unable to decrypt> error with weechat-matrix device and riot device for same account

### ISSUE THREAD

**Issue by gordon-quad** [poljar/weechat-matrix#26]
Steps to reproduce:

1. Create an encrypted room.
2. Invite two accounts both of which use weechat-matrix
3. Add another riot web device to one of those accounts

from time to time it breaks the encryption so one or both weechat-matrix clients cannot read each other but always can read riot messages, sometimes it heals itself after a day of idling but sometimes it is not.
This issue quite intermittent and hard to reproduce so I would really appreciate some help with setting up logging from matrix-nio to be able to debug it.

I am using:
poljar/matrix-nio 9fbe20f6b3f7624d3b8d57a333835fbd641b579d
poljar/python-olm b4c8af18954b6b018c6cef436bd3cc2132b5d2cd
olm-3.0.0
poljar/weechat-matrix branch device-olm 11b960e22c5b191670acc8fee1b36a2ad7c307b4

**Comment by poljar** [comment]
Hi. Thanks for testing weechat-matrix.

Debugging can be configured with the following options:
- matrix.network.debug_buffer
- matrix.network.debug_category
- matrix.network.debug_level

Debugging to a file sadly isn't supported bug could be easily added.

Do you perhaps keep the clients offline before this happens? From your description it seems like you don't get the currently used session key from the other client. The session keys expire after a while or after some amount of sent messages and you get sent new ones, this would explain why it heals itself after a while.

Session keys are shared in special *to_device* events and they don't stay on the server for a long time, if a client misses such an event that contains a session key it is supposed to directly re-request the key from the other client.

Making key requests and handling incoming key requests sadly isn't supported yet.

**Comment by gordon-quad** [comment]
No, both clients are online and the moment one of them logins through riot in addition to existing weechat-matrix client - encryption breaks.
I noticed that your client not yet supports key forwarding but in this case it shouldn't be related to that.

I have seen this debug options, unfortunately it doesn't turn on matrix-nio debug output.
I can set up a mitm proxy to dump client-server communications for one of the client if you find it helpful.

**Comment by gordon-quad** [comment]
And actually I have now a room with this two clients that didn't heal itself for more than a day (I am not so familiar with specification, don't know what actual timeout is) and it has some messages sent to it through riot clients (which btw can be decrypted by both weechat-matrix clients but cannot decrypt weechat-matrix messages)

**Comment by poljar** [comment]
The settings do turn matrix-nio debugging on (I just checked). 

To enable encryption debuggin set the level to debug and the category to encryption or leave it at "all".

So encryption stops working after a new device by riot gets logged in, this is reproducible?

The timeout is quite large (7 days) or 100 messages.

**Comment by gordon-quad** [comment]
ok, steps that I did right now (it is a bit different than described in initial issue):
1. Login with weechat-matrix using account1
2. Login with weechat-matrix using account2
3. Login with Riot IM with account1
4. Create a room and set encryption to true using Riot (i found no way to do that using weechat-matrix).
5. Invite account2 through weechat-client of account1
6. Join and verify all devices.

Result:
- Both of weechat-clients can read messages posed by account1 Riot
- Neither of weechat-clients can read each other's messages
- Riot IM can read weechat-client account1's messages

(That also can be related to the issue #27 that I have submitted because account2 got couple of disconnects during this setup)

**Comment by gordon-quad** [comment]
I also got a log message on account1's weechat but not on account2 weechat:
```
weechat     | nio.encryption: Error decrypting megolm event, no session found with session id
            | XXXXXXXXXXXXXXXX or room !XXXXXXXXXX:homeserver

**Comment by gordon-quad** [comment]
sorry, misclicked the button

**Comment by poljar** [comment]
Thanks, I'll try to reproduce it.

There is currently no way to enabled encryption with weechat, the /room command should be expanded to support this.

It is unlikely that it is related to #27 since the server should keep the required events for such a short period.

**Comment by gordon-quad** [comment]
Tested it with a better connection and verified that there were no disconnects and setup above fully reproduced the issue and I also got message `Error decrypting megolm event, no session found with session id` on both weechat clients now.

**Comment by poljar** [comment]
Ok, I have reproduced the issue and probably found the culprit.

Could you please retest with the latest master of matrix-nio or apply just [this](https://github.com/poljar/matrix-nio/commit/1894114a9f0dcf228a79c598b06918a76f55bb2a) patch on top of your branch?

**Comment by gordon-quad** [comment]
it doesn't start with fresh matrix-nio:
```
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/gordon/.weechat/python/autoload/matrix.py", line 34, in <module>
python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
python: stdout/stderr (?):   File "/usr/lib64/python2.7/site-packages/nio/__init__.py", line 2, in <module>
python: stdout/stderr (?):     from .client import HttpClient, TransportType, Client
python: stdout/stderr (?):   File "/usr/lib64/python2.7/site-packages/nio/client.py", line 46, in <module>
python: stdout/stderr (?):     from .encryption import Olm
python: stdout/stderr (?):   File "/usr/lib64/python2.7/site-packages/nio/encryption.py", line 58, in <module>
python: stdout/stderr (?):     from .crypto import (
python: stdout/stderr (?): ImportError: No module named crypto
```

**Comment by gordon-quad** [comment]
but your patch actually fixed the problem.
I would give it more extensive testing this evening.

**Comment by poljar** [comment]
The package building for latest master should now be fixed as well.
Thanks for testing, I'll leave this open for a while longer.
