### ISSUE TITLE
can't load matrix.py, no module named _sqlite3

### ISSUE THREAD

**Issue by yourfate** [poljar/weechat-matrix#292]
I'm on FreeBSD 13.0, running weechat 3.2. I installed weechat-matrix as described in the wiki. When I try to load it I get this error:

```
python: loading script "/usr/home/yourfate/.weechat/python/matrix.py"
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/usr/home/yourfate/.weechat/python/matrix.py", line 53, in <module>
python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/__init__.py", line 2, in <module>
python: stdout/stderr (?):     from .client import *
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/client/__init__.py", line 3, in <module>
python: stdout/stderr (?):     from .base_client import Client, ClientConfig
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/client/base_client.py", line 35, in <module>
python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/crypto/__init__.py", line 41, in <module>
python: stdout/stderr (?):     from .olm_machine import Olm
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/crypto/olm_machine.py", line 52, in <module>
python: stdout/stderr (?):     from ..store import MatrixStore
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/store/__init__.py", line 35, in <module>
python: stdout/stderr (?):     from .database import (
python: stdout/stderr (?):   File "/home/yourfate/.local/lib/python3.7/site-packages/nio/store/database.py", line 15, in <module>
python: stdout/stderr (?):     import sqlite3
python: stdout/stderr (?):   File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
python: stdout/stderr (?):     from sqlite3.dbapi2 import *
python: stdout/stderr (?):   File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
python: stdout/stderr (?):     from _sqlite3 import *
python: stdout/stderr (?): ModuleNotFoundError: No module named '_sqlite3'
python: unable to parse file "/usr/home/yourfate/.weechat/python/matrix.py"
```

I have installed the requirements with `--user`.

**Comment by yourfate** [comment]
I found the problem, I needed the `py37-sqlite3` package.
