### ISSUE TITLE
Failiure to load script in weechat

### ISSUE THREAD

**Issue by JustSquid** [poljar/weechat-matrix#302]
When I attempt to run the script, it was able to run the first load. On the second however, this error shows up.
`python: loading script
"/home/user/.weechat/python/matrix.py"  
python: stdout/stderr (?):   
Traceback (most recent call last):  
python: stdout/stderr (?):   File "/home/user/.weechat/python/matrix.py", line 55, in <module>  
python: stdout/stderr (?):   from matrix import globals as G  
python: stdout/stderr (?):   ModuleNotFoundError: No module named 'matrix'  
python: unable to parse file "/home/x_x/.weechat/python/matrix.py"  
`
Am I not seeing something right in front of me here?

**Comment by JustSquid** [comment]
To note, the directory pointed to isn't a sym link. Everything was installed to the user .weechat/python directly. I just can't figure out why it doesn't see the matrix module when it's in the same directory.

**Comment by gour** [comment]
I'm getting similar thing:

```
11:51 python: loading script "/home/gour/weechat/python/matrix.py"
11:51 python: stdout/stderr (?): Traceback (most recent call last):
11:51 python: stdout/stderr (?):   File "/home/gour/weechat/python/matrix.py", line 53, in <module>
11:51 python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/nio/__init__.py", line 2, in <module>
11:51 python: stdout/stderr (?):     from .client import *
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/nio/client/__init__.py", line 3, in <module>
11:51 python: stdout/stderr (?):     from .base_client import Client, ClientConfig
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/nio/client/base_client.py", line 35, in <module>
11:51 python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/nio/crypto/__init__.py", line 32, in <module>
11:51 python: stdout/stderr (?):     from .key_request import OutgoingKeyRequest
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/nio/crypto/key_request.py", line 21, in <module>
11:51 python: stdout/stderr (?):     from ..responses import RoomKeyRequestResponse
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/nio/responses.py", line 26, in <module>
11:51 python: stdout/stderr (?):     from jsonschema.exceptions import SchemaError, ValidationError
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/jsonschema/__init__.py", line 21, in <module>
11:51 python: stdout/stderr (?):     from jsonschema._types import TypeChecker
11:51 python: stdout/stderr (?):   File "/home/gour/.local/lib/python3.10/site-packages/jsonschema/_types.py", line 168, in <module>
11:51 python: stdout/stderr (?):     draft3_type_checker = TypeChecker(
11:51 python: stdout/stderr (?): TypeError: TypeChecker() takes no arguments
11:51 =!= python: unable to parse file "/home/gour/weechat/python/matrix.py"
```

trying to run it on Fedora 35 (python-3.10), Weechat-3.3...

Any hint?

**Comment by phi-gamma** [comment]
In case it helps, I just had a similar issue on a nix install that I updated
from the python 3.7 version of the script to 3.9.

After the upgrade I had these two symlinks in ``~/.weechat/python``:

    matrix -> /nix/store/4v77aw85icnjfq5sbyypih4fsmrlm8p7-python3.7-weechat-matrix-unstable-2019-11-10/lib/python3.7/site-packages/matrix
    matrix.py -> /home/philipp/.nix-profile/share/matrix.py

After I removed **both** symlinks and replaced the ``matrix`` one like so:

    matrix -> /nix/store/7idd1d92bz45r6v5jyf41cnfida6h2xp-python3.9-weechat-matrix-0.3.0/lib/python3.9/site-packages/matrix

the issue went away and weechat works normally again.

**Comment by gour** [comment]
> In case it helps, I just had a similar issue on a nix install that I updated
from the python 3.7 version of the script to 3.9.

Hmm...I'm on python-3.10, tried again, but, I'm afraid, it does not help... :disappointed:

**Comment by hkdd** [comment]
Also getting the same error message as gour on Fedora 35.  

The following to packages are installed:
libolm-3.2.6-1.fc35.x86_64
libolm-devel-3.2.6-1.fc35.x86_64

09:43:28            weechat     | python: loading script "/home/user/.weechat/python/matrix.py"
09:43:28            weechat     | python: stdout/stderr (?): Traceback (most recent call last):
09:43:28            weechat     | python: stdout/stderr (?):   File "/home/user/.weechat/python/matrix.py", line 53, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError,
                                | TransportType
09:43:28            weechat     | python: stdout/stderr (?):   File
                                | "/home/user/.local/lib/python3.10/site-packages/nio/__init__.py", line 2, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     from .client import *
09:43:28            weechat     | python: stdout/stderr (?):   File
                                | "/home/user/.local/lib/python3.10/site-packages/nio/client/__init__.py", line 3, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     from .base_client import Client, ClientConfig
09:43:28            weechat     | python: stdout/stderr (?):   File
                                | "/home/user/.local/lib/python3.10/site-packages/nio/client/base_client.py", line 35, in
                                | <module>   
09:43:28            weechat     | python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
09:43:28            weechat     | python: stdout/stderr (?):   File
                                | "/home/user/.local/lib/python3.10/site-packages/nio/crypto/__init__.py", line 32, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     from .key_request import OutgoingKeyRequest
09:43:28            weechat     | python: stdout/stderr (?):   File
                                | "/home/user/.local/lib/python3.10/site-packages/nio/crypto/key_request.py", line 21, in
                                | <module>   
09:43:28            weechat     | python: stdout/stderr (?):     from ..responses import RoomKeyRequestResponse
09:43:28            weechat     | python: stdout/stderr (?):   File
                                | "/home/user/.local/lib/python3.10/site-packages/nio/responses.py", line 26, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     from jsonschema.exceptions import SchemaError, ValidationError
09:43:28            weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/jsonschema/__init__.py",
                                | line 21, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     from jsonschema._types import TypeChecker
09:43:28            weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/jsonschema/_types.py",
                                | line 168, in <module>
09:43:28            weechat     | python: stdout/stderr (?):     draft3_type_checker = TypeChecker(
09:43:28            weechat     | python: stdout/stderr (?): TypeError: TypeChecker() takes no arguments
09:43:28            weechat =!= | python: unable to parse file "/home/user/.weechat/python/matrix.py"
09:43:44            weechat     | python: 3.10.0

**Comment by JustSquid** [comment]
Just discovered a workaround. I had to be in the same directory as the plugin before opening weechat in order to load it properly. Lemme know if this works for you guys as well

**Comment by hkdd** [comment]
Made no difference for me, still get the same error above:

weechat     | python: stdout/stderr (?): TypeError: TypeChecker() takes no arguments
