### ISSUE TITLE
imp module deprecation warning

### ISSUE THREAD

**Issue by craftyguy** [poljar/weechat-matrix#322]
```
  /usr/lib/python3.10/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by jonorthwash** [comment]
This is now a major issue in Debian unstable (Python 3.12), blocking use of weechat-matrix.

```
15:47 python: stdout/stderr (?): Traceback (most recent call last):
15:47 python: stdout/stderr (?):   File "/home/jonathan/.weechat/python/autoload/matrix.py", line 68, in <module>
15:47 python: stdout/stderr (?):     from matrix.commands import (hook_commands, hook_key_bindings, hook_page_up,
15:47 python: stdout/stderr (?):   File "/home/jonathan/.weechat/python/matrix/commands.py", line 24, in <module>
15:47 python: stdout/stderr (?):     from future.moves.itertools import zip_longest
15:47 python: stdout/stderr (?):   File "/usr/lib/python3/dist-packages/future/moves/__init__.py", line 5, in <module>
15:47 python: stdout/stderr (?):     from future.standard_library import import_top_level_modules
15:47 python: stdout/stderr (?):   File "/usr/lib/python3/dist-packages/future/standard_library/__init__.py", line 65, in <module>
15:47 python: stdout/stderr (?):     import imp
15:47 python: stdout/stderr (?): ModuleNotFoundError: No module named 'imp'
15:47 =!= python: unable to parse file "/home/jonathan/.weechat/python/autoload/matrix.py"
```

The Debian team has said that [`python3-future` will not be fixed](https://bugs-devel.debian.org/cgi-bin/bugreport.cgi?bug=1056423).
