### ISSUE TITLE
Issue on alpine linux

### ISSUE THREAD

**Issue by caywin25** [poljar/weechat-matrix#337]
Hello, 

After install weechat-matrix on alpine linux, I have this error on weechat boot when I load weechat-matrix.py script : 

```
20:50 python: loading script "/home/test/.local/share/weechat/python/weechat-matrix.py"
20:50 python: stdout/stderr (?): Traceback (most recent call last):
20:50 python: stdout/stderr (?):   File "/home/test/.local/share/weechat/python/weechat-matrix.py", line 43, in <module>
20:50 python: stdout/stderr (?):     import OpenSSL.crypto as crypto
20:50 python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
20:50 python: stdout/stderr (?):     from OpenSSL import SSL, crypto
20:50 python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/OpenSSL/SSL.py", line 9, in <module>
20:50 python: stdout/stderr (?):     from OpenSSL._util import (
20:50 python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/OpenSSL/_util.py", line 6, in <module>
20:50 python: stdout/stderr (?):     from cryptography.hazmat.bindings.openssl.binding import Binding
20:50 python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
20:50 python: stdout/stderr (?):     from cryptography.hazmat.bindings._openssl import lib
20:50 python: stdout/stderr (?): ModuleNotFoundError: No module named '_cffi_backend'
```
Could you help me please ?
Thank

**Comment by caywin25** [comment]
py3-cffi is already installed.

Thx !

**Comment by caywin25** [comment]
Ok sorry, I just managed to launch it.

Is the configuration of the account in weechat possible when its synapse instance is behind a proxy and accessible with port 443?

If I configure my server via: matrix.server.com:443 weechat returns me a 404: matrix: Error: `LoginInfoError: 404 unknown error`

Thank you

**Comment by caywin25** [comment]
I have this error message on weechat : 

```
python: stdout/stderr (matrix): /home/test/.local/share/weechat/python/autoload/weechat-matrix.py:365: DeprecationWarning: ssl NPN is deprecated, use ALPN instead
python: stdout/stderr (matrix):   server.socket.selected_npn_protocol())
```
Thank you

**Comment by martin-braun** [comment]
@caywin25 How did you manage to get it to run? I installed `weechat-matrix` via NixOS package manager and my script throws `ModuleNotFoundError: No module named '_cffi_backend'` as well.

`cffi` is already satisfied as well.
