### ISSUE TITLE
Outdated nio dependency?

### ISSUE THREAD

**Issue by oatsvine** [poljar/weechat-matrix#355]
I'm getting this error when loading the plugin after a `make install`.
```
         │6  19:01:54     | python: loading script "/home/user/.local/share/weechat/python/matrix.py"
         │7  19:01:55     | python: stdout/stderr (?): Traceback (most recent call last):
         │8  19:01:55     | python: stdout/stderr (?):   File "/home/user/.local/share/weechat/python/matrix.py", line 65, in <module>
         │9  19:01:55     | python: stdout/stderr (?):     from matrix.buffer import room_buffer_close_cb, room_buffer_input_cb
         │10 19:01:55     | python: stdout/stderr (?):   File "/home/user/.local/share/weechat/python/matrix/buffer.py", line 57, in <module>
         │11 19:01:55     | python: stdout/stderr (?):     from .config import RedactType, NewChannelPosition
         │12 19:01:55     | python: stdout/stderr (?):   File "/home/user/.local/share/weechat/python/matrix/config.py", line 61, in <module>
         │13 19:01:55     | python: stdout/stderr (?):     nio.logger_group.level = logbook.ERROR
         │14 19:01:55     | python: stdout/stderr (?):     ^^^^^^^^^^^^^^^^
         │15 19:01:55     | python: stdout/stderr (?): AttributeError: module 'nio' has no attribute 'logger_group'
         │16 19:01:55 =!= | python: unable to parse file "/home/user/.local/share/weechat/python/matrix.py"
```
I'm in the official [matrix debian container](https://github.com/weechat/weechat-container/blob/main/debian/Containerfile), which install python 3.11.

**Comment by poljar** [comment]
Fixed by: https://github.com/poljar/weechat-matrix/pull/353.
