### ISSUE TITLE
Errors upon connecting - olm issue?

### ISSUE THREAD

**Issue by tommyskg** [poljar/weechat-matrix#39]
Upon connecting and logging in (not all rooms gets loaded, but about 22 do) I get the following errors in Weechat. I'm a unsure what the cause is, but the result seems to be that Olm doesn't work.

```
matrix: Logging in...
python: stdout/stderr (colorize_nicks): Traceback (most recent call last):
python: stdout/stderr (matrix): Traceback (most recent call last):
python: stdout/stderr (colorize_nicks):   File "$HOME/.weechat/python/matrix/utf.py", line 91, in wrapper
python: stdout/stderr (matrix):   File "$HOME/.weechat/python/matrix/utf.py", line 91, in wrapper
python: stdout/stderr (colorize_nicks):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
python: stdout/stderr (colorize_nicks):   File "$HOME/.weechat/python/matrix.py", line 308, in receive_cb
python: stdout/stderr (matrix):   File "$HOME/.weechat/python/matrix.py", line 308, in receive_cb
python: stdout/stderr (colorize_nicks):     response = server.client.next_response(MAX_EVENTS)
python: stdout/stderr (matrix):     response = server.client.next_response(MAX_EVENTS)
python: stdout/stderr (colorize_nicks):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 1403, in
                 ╡ next_response
python: stdout/stderr (matrix):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 1403, in next_response
python: stdout/stderr (colorize_nicks):     self.receive_response(response)
python: stdout/stderr (matrix):     self.receive_response(response)
python: stdout/stderr (matrix):     self.receive_response(response)
python: stdout/stderr (colorize_nicks):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 636, in
                 ╡ receive_response
python: stdout/stderr (matrix):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 636, in
                 ╡ receive_response
python: stdout/stderr (colorize_nicks):     self._handle_login(response)
python: stdout/stderr (matrix):     self._handle_login(response)
python: stdout/stderr (colorize_nicks):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 466, in
                 ╡ _handle_login
python: stdout/stderr (matrix):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 466, in _handle_login
python: stdout/stderr (colorize_nicks):     self.load_store()                                                                 
python: stdout/stderr (matrix):     self.load_store()        
python: stdout/stderr (colorize_nicks):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 317, in
                 ╡ load_store
python: stdout/stderr (matrix):   File "$HOME/.local/lib/python2.7/site-packages/nio/client.py", line 317, in load_store
python: stdout/stderr (colorize_nicks):     self.olm = Olm(self.user_id, self.device_id, self.store)                       
python: stdout/stderr (matrix):     self.olm = Olm(self.user_id, self.device_id, self.store)        
python: stdout/stderr (colorize_nicks):   File "$HOME/.local/lib/python2.7/site-packages/nio/crypto/olm_machine.py", line
                 ╡ 140, in __init__
python: stdout/stderr (matrix):   File "$HOME/.local/lib/python2.7/site-packages/nio/crypto/olm_machine.py", line 140, in
                 ╡ __init__
python: stdout/stderr (colorize_nicks):     self.account = OlmAccount()
python: stdout/stderr (matrix):     self.account = OlmAccount()
python: stdout/stderr (colorize_nicks):   File "$HOME/.local/lib/python2.7/site-packages/nio/crypto/sessions.py", line 33, in
                 ╡ __new__
python: stdout/stderr (matrix):   File "$HOME/.local/lib/python2.7/site-packages/nio/crypto/sessions.py", line 33, in __new__
python: stdout/stderr (colorize_nicks):     return super().__new__(cls)
python: stdout/stderr (matrix):     return super().__new__(cls)
python: stdout/stderr (colorize_nicks):   File
                 ╡ "/usr/local/lib/python2.7/site-packages/python_olm-3.0.0-py2.7-openbsd-6.4-amd64.egg/olm/account.py", line 63, in __new__
python: stdout/stderr (matrix):   File
                 ╡ "/usr/local/lib/python2.7/site-packages/python_olm-3.0.0-py2.7-openbsd-6.4-amd64.egg/olm/account.py", line 63, in __new__
python: stdout/stderr (colorize_nicks):     obj._buf = ffi.new("char[]", lib.olm_account_size())
python: stdout/stderr (matrix):     obj._buf = ffi.new("char[]", lib.olm_account_size())
python: stdout/stderr (colorize_nicks): AttributeError: cffi library '_libolm' has no function, constant or global variable
                 ╡ named 'olm_account_size'
python: stdout/stderr (matrix): AttributeError: cffi library '_libolm' has no function, constant or global variable named
                 ╡ 'olm_account_size'
2113  weechat  ⚠ ╡ python: error in function "receive_cb"
```

**Comment by poljar** [comment]
Your python-olm install seems to be broken. Olm account creation errors out because it can't find a symbol in the bindings. Let's continue this in the python-olm issue that you opened.

You can verify this by running this in a python interpreter:
```python
>>> import olm
>>> alice = olm.Account()
>>> alice.identity_keys
{'curve25519': '2PytGagXercwHjzQETLcMa3JOsaU2qkPIESaqoi59zE',
 'ed25519': 'HHpOuFYdHwoa54GxSttz9YmaTmbuVU3js92UTUjYJgM'}
```

If that doesn't error out the same way feel free to reopen this.
