### ISSUE TITLE
/script load matrix.py test fails on OpenBSD

### ISSUE THREAD

**Issue by qbit** [poljar/weechat-matrix#49]
- `virtualenv` in `/usr/local/py-matrix-weechat` (This is for `wxallowed` on OpenBSD) and was configured to use system packages where available.
- `gmake` was used in weechat-matrix to install files .
- Python 2.7.
- Weechat 2.3.
- OLM 3.0.0

`/script load matrix.py test` results in:
```
2019-02-15 06:34:27     =!=     python: unable to parse file "/home/qbit/.weechat/python/matrix.py"
2019-02-15 06:34:27             script: unknown language for script "test"
2019-02-15 06:35:39             python: loading script "/home/qbit/.weechat/python/matrix.py"
2019-02-15 06:35:42             python: stdout/stderr (?): Traceback (most recent call last):
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/home/qbit/.weechat/python/matrix.py", line 34, in <module>
2019-02-15 06:35:42             python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/usr/local/py-matrix-weechat/lib/python2.7/site-packages/nio/__init__.py", line 2, in <module>
2019-02-15 06:35:42             python: stdout/stderr (?):     from .client import HttpClient, TransportType, Client
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/usr/local/py-matrix-weechat/lib/python2.7/site-packages/nio/client.py", line 48, in <module>
2019-02-15 06:35:42             python: stdout/stderr (?):     from .crypto import DeviceStore, Olm
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/usr/local/py-matrix-weechat/lib/python2.7/site-packages/nio/crypto/__init__.py", line 19, in <module>
2019-02-15 06:35:42             python: stdout/stderr (?):     from .olm_machine import Olm
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/usr/local/py-matrix-weechat/lib/python2.7/site-packages/nio/crypto/olm_machine.py", line 74, in <module>
2019-02-15 06:35:42             python: stdout/stderr (?):     from ..responses import (
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/usr/local/py-matrix-weechat/lib/python2.7/site-packages/nio/responses.py", line 640, in <module>
2019-02-15 06:35:42             python: stdout/stderr (?):     class KeysQueryResponse(Response):
2019-02-15 06:35:42             python: stdout/stderr (?):   File "/usr/local/py-matrix-weechat/lib/python2.7/site-packages/nio/responses.py", line 646, in KeysQueryResponse
2019-02-15 06:35:42             python: stdout/stderr (?):     factory=dict
2019-02-15 06:35:42             python: stdout/stderr (?): TypeError: attrib() got an unexpected keyword argument 'factory'
2019-02-15 06:35:42     =!=     python: unable to parse file "/home/qbit/.weechat/python/matrix.py"
```

**Comment by dkasak** [comment]
Can you check what version of the `attrs` Python package you have installed? This is probably caused by a pre-18.1.0 version since the `factory` argument was added [in that version](http://www.attrs.org/en/stable/api.html#attr.ib):

> New in version 18.1.0: factory=f is syntactic sugar for default=attr.Factory(f).

Also that should probably just be `/script load matrix.py`.

**Comment by qbit** [comment]
Ah, I have 17.4.0. I will try updating it.

**Comment by qbit** [comment]
Yep, that did it! Thanks!
