### ISSUE TITLE
crash on invalid utf8

### ISSUE THREAD

**Issue by ara4n** [poljar/weechat-matrix#58]
```
15:30:07     | python: unloading script "matrix"
15:30:08     | python: stdout/stderr (matrix): Traceback (most recent call last):
15:30:08     | python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix.py", line 489, in buffer_switch_cb
15:30:08     | python: stdout/stderr (matrix):     if room_buffer.should_send_read_marker:
15:30:08     | python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/buffer.py", line 919, in should_send_read_marker
15:30:08     | python: stdout/stderr (matrix):
15:30:08     | python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/buffer.py", line 947, in read_markers_enabled
15:30:08     | python: stdout/stderr (matrix):     @property
15:30:08     | python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/config.py", line 354, in str_getter
15:30:08     | python: stdout/stderr (matrix):     return W.config_string(self._option_ptrs[name])
15:30:08     | python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/utf.py", line 56, in hooked
15:30:08     | python: stdout/stderr (matrix):     return decode_from_utf8(result)
15:30:08     | python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/utf.py", line 98, in decode_from_utf8
15:30:08     | python: stdout/stderr (matrix):     return data.decode("utf-8")
15:30:08     | python: stdout/stderr (matrix):   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
15:30:08     | python: stdout/stderr (matrix):     return codecs.utf_8_decode(input, errors, True)
15:30:08     | python: stdout/stderr (matrix): UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
15:30:08 =!= | python: error in function "buffer_switch_cb"
15:30:09     | python: script "matrix" unloaded
```

**Comment by poljar** [comment]
I'm aware of that issue, it only happens when unloading or reloading the script. I didn't figure out the cause of this.

If we don't fix this it will go away once Weechat switches to python3 since the transparent unicode decoding/encoding for callbacks happens only on python2.

**Comment by ReK2Fernandez** [comment]
FYI: arch gnu/linux AUR has a weechat compiled for python3 is outdated but if whoever wants to get proper utf8 you can grab the snapshot locally and modify the version= to the latest stable weechat and then run like normal makepkg, I did this last night and worked without an issue.. make sure you do makepkg -s so it downloads all necessary packages.
