### ISSUE TITLE
Unable to load, libolm.so.2 not found

### ISSUE THREAD

**Issue by craftyguy** [poljar/weechat-matrix#67]
I am unable to load the matrix plugin in weechat, here's the backtrace in weechat after executing `/script load matrix.py`:

```
python: loading script "/home/clayton/.weechat/python/autoload/matrix.py"python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/clayton/.weechat/python/autoload/matrix.py", line 34, in <module>
python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/nio/__init__.py", line 2, in <module>
python: stdout/stderr (?):     from .client import HttpClient, TransportType, Client
python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/nio/client.py", line 48, in <module>
python: stdout/stderr (?):     from .crypto import DeviceStore, Olm
python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/nio/crypto/__init__.py", line 1, in <module>
python: stdout/stderr (?):     from .sessions import (
python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/nio/crypto/sessions.py", line 18, in <module>
python: stdout/stderr (?):     import olm
python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/olm/__init__.py", line 12, in <module>
python: stdout/stderr (?):     from .utility import ed25519_verify, OlmVerifyError
python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/olm/utility.py", line 25, in <module>
python: stdout/stderr (?):     from _libolm import ffi, lib  # type: ignore
python: stdout/stderr (?): ImportError: libolm.so.2: cannot open shared object file: No such file or directory
python: unable to parse file "/home/clayton/.weechat/python/autoload/matrix.py"
```
I have installed libolm from AUR, as instructed in the README, and I'm using the master branch of weechat-matrix (last fetched a few hours ago). libolm in AUR does not provide libolm.so.2:

```
❯ pacman -Ql libolm                                                                                      i
libolm /usr/
libolm /usr/include/
libolm /usr/include/olm/
libolm /usr/include/olm/inbound_group_session.h
libolm /usr/include/olm/olm.h
libolm /usr/include/olm/outbound_group_session.h
libolm /usr/include/olm/pk.h
libolm /usr/lib/
libolm /usr/lib/libolm.so
libolm /usr/lib/libolm.so.3
libolm /usr/lib/libolm.so.3.0.0
```

**Comment by poljar** [comment]
I would guess that you need to rebuild python-olm so it links to `libolm.so.3` instead of `libolm.so.2`.

**Comment by craftyguy** [comment]
Is there a guide somewhere on what all packages need to be built to use this? Obviously libolm is not the only dependency, it seems your matrix-nio project is too? The latest update to the readme in this project makes it sound much simpler than it actually is to use this plugin :(

**Comment by poljar** [comment]
A guide as far as I know no. There is the docker file that somewhat documents the build process, the requirements file also lists all the dependencies. Provided that you have the Olm C library installed pip install should work.

If you are on arch the python-olm as well as the matrix-nio makefiles have targets that build packages for arch.

For python-olm you run `make archpkg`, the packages will be under the packages subdir.

For matrix-nio you run `make arch-git-pkg`, this will also install the packages for you after building.

**Comment by poljar** [comment]
Oh right, someone mentioned in the project chat room that he'll put those PKGBUILDS on the AUR as well as make a weechat-matrix PKGBUILD. 

Don't know how far that got, but that would probably solve most problems people have at least for Arch.

**Comment by craftyguy** [comment]
Thanks, I got things to load now, but I'm now getting a different error from matrix.py:

```
12:53:11 weechat     | python: loading script "/home/clayton/.weechat/python/autoload/matrix.py"12:53:13 weechat     | python: registered script "matrix", version 0.1 (matrix chat plugin)12:53:13 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper12:53:13 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 1558, in        ┆       ┆    | matrix_config_server_change_cb12:53:13 weechat     | python: stdout/stderr (matrix):     server.update_option(option, option_name)12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 365, in update_option12:53:13 weechat     | python: stdout/stderr (matrix):     self._change_client() 
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 360, in _change_client
12:53:13 weechat     | python: stdout/stderr (matrix):     extra_path=extra_path 
12:53:13 weechat     | python: stdout/stderr (matrix): TypeError: __init__() got an unexpected keyword argument 'extra_path'
12:53:13 weechat =!= | python: error in function "matrix_config_server_change_cb"
12:53:13 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:13 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 1558, in
        ┆       ┆    | matrix_config_server_change_cb
12:53:13 weechat     | python: stdout/stderr (matrix):     server.update_option(option, option_name)
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 367, in update_option
12:53:13 weechat     | python: stdout/stderr (matrix):     self._change_client() 
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 360, in _change_client
12:53:13 weechat     | python: stdout/stderr (matrix):     extra_path=extra_path 
12:53:13 weechat     | python: stdout/stderr (matrix): TypeError: __init__() got an unexpected keyword argument 'extra_path'
12:53:13 weechat =!= | python: error in function "matrix_config_server_change_cb"
12:53:13 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:13 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 1558, in
        ┆       ┆    | matrix_config_server_change_cb
12:53:13 weechat     | python: stdout/stderr (matrix):     server.update_option(option, option_name)
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 365, in update_option
12:53:13 weechat     | python: stdout/stderr (matrix):     self._change_client() 
12:53:13 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 360, in _change_client
12:53:13 weechat     | python: stdout/stderr (matrix):     extra_path=extra_path 
12:53:13 weechat     | python: stdout/stderr (matrix): TypeError: __init__() got an unexpected keyword argument 'extra_path'
12:53:13 weechat =!= | python: error in function "matrix_config_server_change_cb"
12:53:13 disroot  -- | matrix: Connecting to disroot.org:443 (SSL)...
12:53:14 disroot  -- | matrix: Doing SSL handshake...
12:53:15 disroot  -- | matrix: Connected using TLSv1.2, and 256 bit ECDHE-RSA-CHACHA20-POLY1305 cipher suite.
12:53:15 disroot  -- | matrix: received certificate
12:53:15 disroot     |  - certificate info:
12:53:15 disroot     |     - subject: commonName=disroot.org, serial number
12:53:15 disroot     |         039027230AC27517C5DC2D17B5C97125A7AA
12:53:15 disroot     |     - issuer: countryName=US, organizationName=Let's Encrypt,
12:53:15 disroot     |         commonName=Let's Encrypt Authority X3
12:53:15 disroot     |     - key info: RSA key 4096 bits, signed using
12:53:15 disroot     |         sha256WithRSAEncryption
12:53:15 disroot     |     - period of validity:
12:53:15 disroot     |         Begins on:  Feb 10 23:06:36 2019 GMT
12:53:15 disroot     |         Expires on: May 11 23:06:36 2019 GMT
12:53:15 disroot     |     - fingerprints:
12:53:15 disroot     |         SHA1:   24:86:42:BF:66:F3:1B:CC:DE:CE:42:DC:F6:B5:C8:B3:8B:07:31:18
12:53:15 disroot     |         SHA256: D2:27:65:EA:1B:DA:7B:CC:0F:0D:40:07:17:22:D8:AB:3A:C0:6C:9F:DA:B8:A5:35:7A:FE:B1:07:5C:7A:F4:0D
12:53:15 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:15 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:15 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:15 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/autoload/matrix.py", line 199, in ssl_fd_cb
12:53:15 weechat     | python: stdout/stderr (matrix):     try_ssl_handshake(server)
12:53:15 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/autoload/matrix.py", line 224, in
        ┆       ┆    | try_ssl_handshake
12:53:15 weechat     | python: stdout/stderr (matrix):     finalize_connection(server)
12:53:15 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/autoload/matrix.py", line 347, in
        ┆       ┆    | finalize_connection
12:53:15 weechat     | python: stdout/stderr (matrix):     data = server.client.connect(server.transport_type)
12:53:15 weechat     | python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'connect'
12:53:15 weechat =!= | python: error in function ""
12:53:15 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:15 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:15 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:15 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/autoload/matrix.py", line 303, in receive_cb
12:53:15 weechat     | python: stdout/stderr (matrix):     server.client.receive(data)
12:53:15 weechat     | python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'receive'
12:53:15 weechat =!= | python: error in function "receive_cb"
12:53:16 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:16 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:16 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:16 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 1625, in matrix_timer_cb
12:53:16 weechat     | python: stdout/stderr (matrix):     server.lag = server.client.lag * 1000
12:53:16 weechat     | python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'lag'
12:53:16 weechat =!= | python: error in function "matrix_timer_cb"
12:53:17 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:17 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:17 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:17 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 1625, in matrix_timer_cb
12:53:17 weechat     | python: stdout/stderr (matrix):     server.lag = server.client.lag * 1000
12:53:17 weechat     | python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'lag'
```

**Comment by craftyguy** [comment]
Forgot to mention in the previous comment, but it goes on to repeat this many times, about once every second:

```
12:53:16 weechat =!= | python: error in function "matrix_timer_cb"
12:53:17 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
12:53:17 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/utf.py", line 91, in wrapper
12:53:17 weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:53:17 weechat     | python: stdout/stderr (matrix):   File "/home/clayton/.weechat/python/matrix/server.py", line 1625, in matrix_timer_cb
12:53:17 weechat     | python: stdout/stderr (matrix):     server.lag = server.client.lag * 1000
12:53:17 weechat     | python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'lag'
```

It never does connect to the matrix server.

**Comment by poljar** [comment]
It seems like you installed the tagged version of matrix-nio with `make archpkg` instead of the git version with `make arch-git-pkg`.

**Comment by craftyguy** [comment]
Ah, sorry, I'll try the git version!

**Comment by craftyguy** [comment]
It appears that all issues are resolved now. Thanks for the help!!

**Comment by poljar** [comment]
No problem.
