### ISSUE TITLE
[error] AttributeError: 'NoneType' object has no attribute 'get_binary_type

### ISSUE THREAD

**Issue by parisni** [poljar/weechat-matrix#77]
Hi all

I have a fresh install (master branch) on a weechat 2.4 shipped with python 2.7.
The `/matrix connect matrix_org` command returns this error:
Any thought ?

Thanks
```
12:54 -- freenode-connect (frigg@freenode/utility-bot/frigg): Welcome to freenode. To protect the network all new connections will be scanned for vulnerabilities. This will not harm your computer, and vulnerable hosts will be notified.
12:54 -- CTCP requested by freenode-connect: VERSION (blocked)
12:54 -- #security: ##security :Forwarding to another channel
12:54 python: loading script "/home/parisni/.weechat/python/matrix.py"
12:54 python: registered script "matrix", version 0.1 (matrix chat plugin)
12:54 -- matrix: Connecting to matrix.org:443 (SSL)...
12:54 -- matrix: Doing SSL handshake...
12:54 -- matrix: Connected using TLSv1.3, and 256 bit TLS_AES_256_GCM_SHA384 cipher suite.
12:54 -- matrix: received certificate
12:54  - certificate info:
12:54     - subject: commonName=www.matrix.org, serial number
12:54         03F40B355432D2DC89D5506299C1DE90418C
12:54     - issuer: countryName=US, organizationName=Let's Encrypt,
12:54         commonName=Let's Encrypt Authority X3
12:54     - key info: RSA key 4096 bits, signed using
12:54         sha256WithRSAEncryption
12:54     - period of validity:
12:54         Begins on:  Apr 11 10:43:45 2019 GMT
12:54         Expires on: Jul 10 10:43:45 2019 GMT
12:54     - fingerprints:
12:54         SHA1:   56:94:4A:54:90:66:A9:98:97:B1:DE:35:56:6E:E4:CE:D6:B4:94:81
12:54         SHA256: 3E:AD:E4:5B:89:F6:4A:D1:67:38:5B:40:D0:F4:E2:5C:89:34:1D:91:7A:8F:02:F2:47:CB:4C:95:A4:64:A3:A2
12:54 -- matrix: Logging in...
12:54 python: stdout/stderr (matrix): Traceback (most recent call last):
12:54 python: stdout/stderr (matrix):   File "/home/parisni/.weechat/python/matrix/utf.py", line 91, in wrapper
12:54 python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:54 python: stdout/stderr (matrix):   File "/home/parisni/.weechat/python/matrix.py", line 309, in receive_cb
12:54 python: stdout/stderr (matrix):     response = server.client.next_response(MAX_EVENTS)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/nio/client/http_client.py", line 826, in next_response
12:54 python: stdout/stderr (matrix):     self.receive_response(response)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/nio/client/base_client.py", line 610, in receive_response
12:54 python: stdout/stderr (matrix):     self._handle_login(response)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/nio/client/base_client.py", line 401, in _handle_login
12:54 python: stdout/stderr (matrix):     self.load_store()
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/nio/client/base_client.py", line 248, in load_store
12:54 python: stdout/stderr (matrix):     self.config.store_name
12:54 python: stdout/stderr (matrix):   File "<attrs generated init 5f027665cfdf70b24c9883f3edf2cdb2800261b7>", line 7, in __init__
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/nio/store/database.py", line 872, in __attrs_post_init__
12:54 python: stdout/stderr (matrix):     super().__attrs_post_init__()
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/nio/store/database.py", line 533, in __attrs_post_init__
12:54 python: stdout/stderr (matrix):     self.database.create_tables(self.models)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/peewee.py", line 5829, in __exit__
12:54 python: stdout/stderr (matrix):     model.bind(db, self.bind_refs, self.bind_backrefs)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/peewee.py", line 6175, in bind
12:54 python: stdout/stderr (matrix):     cls._meta.set_database(database)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/peewee.py", line 5667, in set_database
12:54 python: stdout/stderr (matrix):     hook(database)
12:54 python: stdout/stderr (matrix):   File "/home/parisni/git/weechat-matrix/venv2/lib/python2.7/site-packages/peewee.py", line 4422, in _db_hook
12:54 python: stdout/stderr (matrix):     self._constructor = database.get_binary_type()
12:54 python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'get_binary_type'
12:54:35    weechat =!= | python: error in function "receive_cb"
```

**Comment by poljar** [comment]
This is a peewee bug: https://github.com/coleifer/peewee/issues/1913
The next peewee release fixes this.

**Comment by parisni** [comment]
upgrading peewee to 3.9.5 fixed the issue. thanks a lot !
