### ISSUE TITLE
Error while sending encrypted messages

### ISSUE THREAD

**Issue by BurnyBoi** [poljar/weechat-matrix#79]
I was able to send 1 encrypted message, but then after that, I get the following error while trying to:

```
weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
weechat     | python: stdout/stderr (matrix):   File "/home/user/.weechat/python/matrix/utf.py", line 91, in wrapper
weechat     | python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
weechat     | python: stdout/stderr (matrix):   File "/home/user/.weechat/python/matrix.py", line 318, in receive_cb
weechat     | python: stdout/stderr (matrix):     server.handle_response(response)
weechat     | python: stdout/stderr (matrix):   File "/home/user/.weechat/python/matrix/server.py", line 1420, in handle_response
weechat     | python: stdout/stderr (matrix):     self.encryption_queue[room_id].appendleft(message)
weechat     | python: stdout/stderr (matrix): UnboundLocalError: local variable 'message' referenced before assignment
weechat =!= | python: error in function "receive_cb"
```

**Comment by poljar** [comment]
Yes, there's a  bug in the way we queue messages for encryption, especially if there's a lot of users/devices in a room. I haven't had the chance yet to figure it out.
