### ISSUE TITLE
Error while loading rooms with python3

### ISSUE THREAD

**Issue by BurnyBoi** [poljar/weechat-matrix#87]
I just tried to switch from using python2 to python3 in weechat, but I noticed right after logging in, when weechat is syncing and loading the rooms, I get this error in the weechat buffer:

```
│14:56:19 weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/home/user/.weechat/python/matrix/utf.py", line 89, in wrapper
│14:56:19 weechat     | python: stdout/stderr (matrix):     return function(*args, **kwargs)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/home/user/.weechat/python/autoload/matrix.py", line 309, in receive_cb
│14:56:19 weechat     | python: stdout/stderr (matrix):     response = server.client.next_response(MAX_EVENTS)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/usr/lib/python3.7/site-packages/nio/client/http_client.py", line 826, in
│                     | next_response
│14:56:19 weechat     | python: stdout/stderr (matrix):     self.receive_response(response)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/usr/lib/python3.7/site-packages/nio/client/base_client.py", line 611, in
│                     | receive_response
14:56:19 weechat     | python: stdout/stderr (matrix):     self._handle_sync(response)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/usr/lib/python3.7/site-packages/nio/client/base_client.py", line 487, in
│                     | _handle_sync
│14:56:19 weechat     | python: stdout/stderr (matrix):     new_event = self.olm.decrypt_event(event)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/usr/lib/python3.7/site-packages/nio/crypto/olm_machine.py", line 876, in
│                     | decrypt_event
│14:56:19 weechat     | python: stdout/stderr (matrix):     return self.decrypt_megolm_event(event)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/usr/lib/python3.7/site-packages/nio/crypto/olm_machine.py", line 771, in
│                     | decrypt_megolm_event
│14:56:19 weechat     | python: stdout/stderr (matrix):     plaintext, message_index = session.decrypt(event.ciphertext)
│14:56:19 weechat     | python: stdout/stderr (matrix):   File "/usr/lib/python3.7/site-packages/olm/group_session.py", line 232, in decrypt
│14:56:19 weechat     | python: stdout/stderr (matrix):     lib.memset(plaintext_buffer, 0, max_plaintext_length)
│14:56:19 weechat     | python: stdout/stderr (matrix): AttributeError: cffi library '_libolm' has no function, constant or global variable named
│                     | 'memset'
│14:56:19 weechat =!= | python: error in function "receive_cb"
```

If I wait a minute or 2, weechat logs into the matrix server again, and some of my rooms will actually load on the left nav, but most won't.

**Comment by BurnyBoi** [comment]
Just double-checked that I have libolm installed. I installed it from the AUR.

**Comment by poljar** [comment]
That's an issue with python-olm. Make sure you have the latest one installed and you'll have to restart Weechat after you reinstall it to pick up the changed lib.

**Comment by BurnyBoi** [comment]
I just tried to grab the latest python-olm with `pip3 install --upgrade python-olm`, and I get:

```
Requirement already up-to-date: python-olm in /usr/lib/python3.7/site-packages (3.1.0)
Requirement already satisfied, skipping upgrade: cffi>=1.0.0 in /usr/lib/python3.7/site-packages (from python-olm) (1.12.3)
Requirement already satisfied, skipping upgrade: future in /usr/lib/python3.7/site-packages (from python-olm) (0.17.1)
Requirement already satisfied, skipping upgrade: pycparser in /usr/lib/python3.7/site-packages (from cffi>=1.0.0->python-olm) (2.19)
```

**Comment by poljar** [comment]
Does python-olm work in a normal python interpreter? You did restart weechat?

**Comment by BurnyBoi** [comment]
I have restarted weechat yes. I have python-olm 3.1.0, and it looks like trying to upgrade it above didn't really do anything since I already had it before. Any suggestions on the quickest method for testing it in a python interpreter?

**Comment by BurnyBoi** [comment]
Okay, rather than trying to upgrade it, I just uninstalled it with pip, and reinstalled, and now it's fine...

**Comment by poljar** [comment]
There's also an AUR package for python-olm which I maintain. Glad it worked out.
